@echo off
echo Renaming Halo 2 Icons...
echo.

REM ===== KEYBOARD =====
if exist "00E0.bmp" ren "00E0.bmp" "Wink.bmp"
if exist "02E0.bmp" ren "02E0.bmp" "Neutral.bmp"
if exist "01E0.bmp" ren "01E0.bmp" "Big Smile.bmp"
if exist "04E0.bmp" ren "04E0.bmp" "Tongue.bmp"
if exist "0526.bmp" ren "0526.bmp" "Star.bmp"
if exist "9126.bmp" ren "9126.bmp" "Flag Symbol.bmp"
if exist "1327.bmp" ren "1327.bmp" "Check.bmp"
if exist "1727.bmp" ren "1727.bmp" "X Symbol.bmp"

REM ===== MISCELLANEOUS =====
if exist "05E0.bmp" ren "05E0.bmp" "Camera.bmp"
if exist "06E0.bmp" ren "06E0.bmp" "Guest.bmp"
if exist "07E0.bmp" ren "07E0.bmp" "Downloadable Content.bmp"
if exist "08E0.bmp" ren "08E0.bmp" "Lock.bmp"

REM ===== INGAME MEDALS =====
if exist "33E0.bmp" ren "33E0.bmp" "Killing Spree.bmp"
if exist "34E0.bmp" ren "34E0.bmp" "Running Riot.bmp"
if exist "35E0.bmp" ren "35E0.bmp" "Rampage.bmp"
if exist "36E0.bmp" ren "36E0.bmp" "Berserker.bmp"
if exist "37E0.bmp" ren "37E0.bmp" "Overkill.bmp"
if exist "38E0.bmp" ren "38E0.bmp" "Double Kill.bmp"
if exist "39E0.bmp" ren "39E0.bmp" "Triple Kill.bmp"
if exist "40E0.bmp" ren "40E0.bmp" "Killtacular.bmp"
if exist "41E0.bmp" ren "41E0.bmp" "Kill Frenzy.bmp"
if exist "42E0.bmp" ren "42E0.bmp" "Killtrocity.bmp"
if exist "43E0.bmp" ren "43E0.bmp" "Killamanjaro.bmp"
if exist "44E0.bmp" ren "44E0.bmp" "Sniper Kill.bmp"
if exist "45E0.bmp" ren "45E0.bmp" "Roadkill.bmp"
if exist "46E0.bmp" ren "46E0.bmp" "Bonecracker.bmp"
if exist "47E0.bmp" ren "47E0.bmp" "Assassin.bmp"
if exist "48E0.bmp" ren "48E0.bmp" "Stick It.bmp"
if exist "49E0.bmp" ren "49E0.bmp" "Flag Carrier Kill.bmp"
if exist "50E0.bmp" ren "50E0.bmp" "Oddball Carrier Kill.bmp"
if exist "51E0.bmp" ren "51E0.bmp" "Bomb Carrier Kill.bmp"
if exist "52E0.bmp" ren "52E0.bmp" "Do Not Enter.bmp"
if exist "53E0.bmp" ren "53E0.bmp" "Carjacking.bmp"
if exist "54E0.bmp" ren "54E0.bmp" "Flag Taken.bmp"
if exist "55E0.bmp" ren "55E0.bmp" "Bomb Taken.bmp"
if exist "56E0.bmp" ren "56E0.bmp" "Flag Captured.bmp"
if exist "57E0.bmp" ren "57E0.bmp" "Bomb Planted.bmp"
if exist "58E0.bmp" ren "58E0.bmp" "Flag Returned.bmp"
if exist "59E0.bmp" ren "59E0.bmp" "Bomb Returned.bmp"
if exist "60E0.bmp" ren "60E0.bmp" "Question Mark.bmp"

REM ===== POSTGAME MEDALS =====
if exist "65E0.bmp" ren "65E0.bmp" "Killing Spree (Post).bmp"
if exist "66E0.bmp" ren "66E0.bmp" "Running Riot (Post).bmp"
if exist "67E0.bmp" ren "67E0.bmp" "Rampage (Post).bmp"
if exist "68E0.bmp" ren "68E0.bmp" "Berserker (Post).bmp"
if exist "69E0.bmp" ren "69E0.bmp" "Overkill (Post).bmp"
if exist "70E0.bmp" ren "70E0.bmp" "Double Kill (Post).bmp"
if exist "71E0.bmp" ren "71E0.bmp" "Triple Kill (Post).bmp"
if exist "72E0.bmp" ren "72E0.bmp" "Killtacular (Post).bmp"
if exist "73E0.bmp" ren "73E0.bmp" "Kill Frenzy (Post).bmp"
if exist "74E0.bmp" ren "74E0.bmp" "Killtrocity (Post).bmp"
if exist "75E0.bmp" ren "75E0.bmp" "Killamanjaro (Post).bmp"
if exist "76E0.bmp" ren "76E0.bmp" "Sniper Kill (Post).bmp"
if exist "77E0.bmp" ren "77E0.bmp" "Roadkill (Post).bmp"
if exist "78E0.bmp" ren "78E0.bmp" "Bonecracker (Post).bmp"
if exist "79E0.bmp" ren "79E0.bmp" "Assassin (Post).bmp"
if exist "80E0.bmp" ren "80E0.bmp" "Stick It (Post).bmp"
if exist "81E0.bmp" ren "81E0.bmp" "Carjacking (Post).bmp"
if exist "82E0.bmp" ren "82E0.bmp" "Do Not Enter (Post).bmp"
if exist "83E0.bmp" ren "83E0.bmp" "Flag Carrier Kill (Post).bmp"
if exist "84E0.bmp" ren "84E0.bmp" "Oddball Carrier Kill (Post).bmp"
if exist "85E0.bmp" ren "85E0.bmp" "Bomb Carrier Kill (Post).bmp"
if exist "86E0.bmp" ren "86E0.bmp" "Flag Taken (Post).bmp"
if exist "87E0.bmp" ren "87E0.bmp" "Bomb Taken (Post).bmp"
if exist "88E0.bmp" ren "88E0.bmp" "Flag Captured (Post).bmp"
if exist "89E0.bmp" ren "89E0.bmp" "Bomb Planted (Post).bmp"
if exist "90E0.bmp" ren "90E0.bmp" "Flag Returned (Post).bmp"
if exist "91E0.bmp" ren "91E0.bmp" "Bomb Returned (Post).bmp"
if exist "92E0.bmp" ren "92E0.bmp" "Large Question Mark (Post).bmp"

REM ===== BUTTONS =====
if exist "00E1.bmp" ren "00E1.bmp" "A Button.bmp"
if exist "01E1.bmp" ren "01E1.bmp" "B Button.bmp"
if exist "02E1.bmp" ren "02E1.bmp" "X Button.bmp"
if exist "03E1.bmp" ren "03E1.bmp" "Y Button.bmp"
if exist "04E1.bmp" ren "04E1.bmp" "Black Button.bmp"
if exist "05E1.bmp" ren "05E1.bmp" "White Button.bmp"
if exist "0CE1.bmp" ren "0CE1.bmp" "Start.bmp"
if exist "0DE1.bmp" ren "0DE1.bmp" "Back.bmp"
if exist "06E1.bmp" ren "06E1.bmp" "Left Trigger.bmp"
if exist "07E1.bmp" ren "07E1.bmp" "Right Trigger.bmp"
if exist "08E1.bmp" ren "08E1.bmp" "Up.bmp"
if exist "09E1.bmp" ren "09E1.bmp" "Down.bmp"
if exist "0AE1.bmp" ren "0AE1.bmp" "Left.bmp"
if exist "0BE1.bmp" ren "0BE1.bmp" "Right.bmp"
if exist "2DE1.bmp" ren "2DE1.bmp" "Left Thumbstick.bmp"
if exist "10E1.bmp" ren "10E1.bmp" "Left Thumbstick Up.bmp"
if exist "0EE1.bmp" ren "0EE1.bmp" "Left Thumbstick Down.bmp"
if exist "59E4.bmp" ren "59E4.bmp" "L Thumbstick Animated.bmp"
if exist "30E1.bmp" ren "30E1.bmp" "Right Thumbstick.bmp"
if exist "11E1.bmp" ren "11E1.bmp" "Right Thumbstick Up.bmp"
if exist "0FE1.bmp" ren "0FE1.bmp" "Right Thumbstick Down.bmp"
if exist "5AE4.bmp" ren "5AE4.bmp" "R Thumbstick Animated.bmp"

REM ===== WEAPONS - Objective =====
if exist "16E1.bmp" ren "16E1.bmp" "Flag (Weapon).bmp"
if exist "13E1.bmp" ren "13E1.bmp" "Bomb (Weapon).bmp"
if exist "1CE1.bmp" ren "1CE1.bmp" "Oddball.bmp"

REM ===== WEAPONS - Human =====
if exist "1AE1.bmp" ren "1AE1.bmp" "Magnum.bmp"
if exist "22E1.bmp" ren "22E1.bmp" "SMG.bmp"
if exist "2BE1.bmp" ren "2BE1.bmp" "SMG Long Barrel.bmp"
if exist "12E1.bmp" ren "12E1.bmp" "Battle Rifle.bmp"
if exist "21E1.bmp" ren "21E1.bmp" "Shotgun.bmp"
if exist "23E1.bmp" ren "23E1.bmp" "Sniper Rifle.bmp"
if exist "20E1.bmp" ren "20E1.bmp" "Rocket Launcher.bmp"

REM ===== WEAPONS - Covenant =====
if exist "1DE1.bmp" ren "1DE1.bmp" "Plasma Pistol.bmp"
if exist "1EE1.bmp" ren "1EE1.bmp" "Plasma Rifle.bmp"
if exist "2AE1.bmp" ren "2AE1.bmp" "Brute Plasma Rifle.bmp"
if exist "1BE1.bmp" ren "1BE1.bmp" "Needler.bmp"
if exist "15E1.bmp" ren "15E1.bmp" "Carbine.bmp"
if exist "14E1.bmp" ren "14E1.bmp" "Brute Shot.bmp"
if exist "1FE1.bmp" ren "1FE1.bmp" "Energy Sword.bmp"
if exist "24E1.bmp" ren "24E1.bmp" "Beam Rifle.bmp"
if exist "17E1.bmp" ren "17E1.bmp" "Fuel Rod Gun.bmp"
if exist "26E1.bmp" ren "26E1.bmp" "Sentinel Beam.bmp"
if exist "27E1.bmp" ren "27E1.bmp" "Sentinel Beam 3 Lines.bmp"
if exist "28E1.bmp" ren "28E1.bmp" "Sentinel Beam 2 Balls.bmp"
if exist "29E1.bmp" ren "29E1.bmp" "Sentinel Beam Contrail.bmp"

REM ===== WEAPONS - Unknown =====
if exist "25E1.bmp" ren "25E1.bmp" "Unknown Gun 1.bmp"
if exist "19E1.bmp" ren "19E1.bmp" "Unknown Gun 2.bmp"
if exist "18E1.bmp" ren "18E1.bmp" "Flamethrower.bmp"

REM ===== VARIABLES =====
if exist "0AE4.bmp" ren "0AE4.bmp" "Game Name.bmp"
if exist "0BE4.bmp" ren "0BE4.bmp" "Radar OnOff.bmp"
if exist "0CE4.bmp" ren "0CE4.bmp" "Team Play.bmp"
if exist "1FE4.bmp" ren "1FE4.bmp" "Connection Type.bmp"
if exist "2DE4.bmp" ren "2DE4.bmp" "Your Score.bmp"
if exist "2EE4.bmp" ren "2EE4.bmp" "Enemy Score.bmp"
if exist "3AE4.bmp" ren "3AE4.bmp" "Last Matchmade Game.bmp"
if exist "3BE4.bmp" ren "3BE4.bmp" "Matchmade Disc.bmp"
if exist "05E4.bmp" ren "05E4.bmp" "Align Text Left.bmp"
if exist "06E4.bmp" ren "06E4.bmp" "Align Text Right.bmp"
if exist "07E4.bmp" ren "07E4.bmp" "Center Text.bmp"
if exist "08E4.bmp" ren "08E4.bmp" "Map.bmp"
if exist "09E4.bmp" ren "09E4.bmp" "Gametype.bmp"
if exist "0FE4.bmp" ren "0FE4.bmp" "Controller 1 Profile.bmp"
if exist "10E4.bmp" ren "10E4.bmp" "Controller 2 Profile.bmp"
if exist "11E4.bmp" ren "11E4.bmp" "Controller 3 Profile.bmp"
if exist "12E4.bmp" ren "12E4.bmp" "Controller 4 Profile.bmp"
if exist "13E4.bmp" ren "13E4.bmp" "Game Start Countdown.bmp"
if exist "14E4.bmp" ren "14E4.bmp" "Countdown Delay Player.bmp"
if exist "16E4.bmp" ren "16E4.bmp" "Party Leader.bmp"
if exist "21E4.bmp" ren "21E4.bmp" "Clan.bmp"
if exist "22E4.bmp" ren "22E4.bmp" "Rounds Picked Up.bmp"
if exist "23E4.bmp" ren "23E4.bmp" "Game Timer.bmp"
if exist "25E4.bmp" ren "25E4.bmp" "Players in Party.bmp"
if exist "29E4.bmp" ren "29E4.bmp" "Individual Player.bmp"

REM ===== COLOR BLOCKS =====
if exist "10E0.bmp" ren "10E0.bmp" "Color White.bmp"
if exist "11E0.bmp" ren "11E0.bmp" "Color Steel.bmp"
if exist "12E0.bmp" ren "12E0.bmp" "Color Red.bmp"
if exist "13E0.bmp" ren "13E0.bmp" "Color Orange.bmp"
if exist "14E0.bmp" ren "14E0.bmp" "Color Gold.bmp"
if exist "15E0.bmp" ren "15E0.bmp" "Color Olive.bmp"
if exist "16E0.bmp" ren "16E0.bmp" "Color Green.bmp"
if exist "17E0.bmp" ren "17E0.bmp" "Color Sage.bmp"
if exist "18E0.bmp" ren "18E0.bmp" "Color Cyan.bmp"
if exist "27E0.bmp" ren "27E0.bmp" "Color Teal.bmp"
if exist "19E0.bmp" ren "19E0.bmp" "Color Cobalt.bmp"
if exist "1FE0.bmp" ren "1FE0.bmp" "Color Blue.bmp"
if exist "20E0.bmp" ren "20E0.bmp" "Color Violet.bmp"
if exist "22E0.bmp" ren "22E0.bmp" "Color Purple.bmp"
if exist "23E0.bmp" ren "23E0.bmp" "Color Pink.bmp"
if exist "24E0.bmp" ren "24E0.bmp" "Color Crimson.bmp"
if exist "25E0.bmp" ren "25E0.bmp" "Color Brown.bmp"
if exist "26E0.bmp" ren "26E0.bmp" "Color Tan.bmp"

REM ===== SPECIAL FILES =====
if exist "0000.bmp" ren "0000.bmp" "Blank.bmp"
if exist "FFFF.bmp" ren "FFFF.bmp" "Separator.bmp"

REM ===== Handle GIF file =====
if exist "51E0.gif" ren "51E0.gif" "Bomb Carrier Kill.gif"

echo.
echo Done! Icons have been renamed.
pause
